matheusjerico_bigquery_project:
  outputs:
    dev:
      dataset: "{{ env_var('DBT_GCP_DATASET') }}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('DBT_GCP_JSON_KEY_FILE') }}"
      location: US
      method: service-account
      priority: interactive
      project: "{{ env_var('DBT_GCP_PROJECT') }}"
      threads: 1
      type: bigquery
  target: dev
