matheusjerico_bigquery_project:
  outputs:
    dev:
      dataset: dbt_tutorial
      # dataset: "{{ env_var('DBT_GCP_DATASET') }}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      # keyfile: /home/magalu/.dbt/sa_key_file.json
      keyfile: "{{ env_var('DBT_GCP_JSON_KEY_FILE_LOCATION') }}"
      location: US
      method: service-account
      priority: interactive
      project: dbt-tutorial-matheusjerico
      # project: "{{ env_var('DBT_GCP_PROJECT') }}"
      threads: 1
      type: bigquery
  target: dev
