matheusjerico_bigquery_project:
  outputs:
    dev:
      dataset: dbt_tutorial
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('DBT_GCP_JSON_KEY_FILE_LOCATION') }}"
      location: US
      method: service-account
      priority: interactive
      project: dbt-tutorial-matheusjerico
      threads: 1
      type: bigquery
  target: dev
