name: dbt_ci_cd

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

env:
  DBT_GCP_DATASET: ${{ secrets.GCP_DATASET }}
  DBT_GCP_JSON_KEY_FILE: ${{ secrets.DBT_GCP_JSON_KEY_FILE }}
  DBT_GCP_PROJECT: ${{ secrets.GCP_PROJECT }}

jobs:
  dbt-ci-cd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.x'

    - name: Install dbt
      run: |
        python -m pip install --upgrade pip
        pip install dbt-core dbt-bigquery

    - name: Set up Google Cloud authentication
      env:
        DBT_KEYFILE: ${{ secrets.DBT_GCP_JSON_KEY_FILE }}
      run: |
        echo "$DBT_KEYFILE" > /tmp/sa_key_file.json
        export GOOGLE_APPLICATION_CREDENTIALS=/tmp/sa_key_file.json

    - name: Run dbt models
      run: |
        dbt deps --target dev
        dbt seed --target dev
        dbt run --target dev

    - name: Test dbt models
      run: |
        dbt test --target dev