name: dbt_ci_cd

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

env:
  DBT_PROJECT_DIR: ./
  DBT_PROFILES_DIR: ./
  DBT_GCP_JSON_KEY_FILE_LOCATION: /tmp/sa_key_file.json
  DBT_GCP_JSON_KEY_FILE: ${{ secrets.DBT_GCP_JSON_KEY_FILE }}

jobs:
  dbt_ci_cd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.x'

    - name: Install dbt
      run: |
        python -m pip install --upgrade pip
        pip install dbt-core==1.7.18 dbt-bigquery==1.7.9

    - name: Set up Google Cloud authentication
      env:
        DBT_KEYFILE: ${{ secrets.DBT_GCP_JSON_KEY_FILE }}
      run: |
        echo "$DBT_KEYFILE" > /tmp/sa_key_file.json
        export GOOGLE_APPLICATION_CREDENTIALS=/tmp/sa_key_file.json

    - name: Run dbt models
      run: |
        dbt deps
        dbt seed
        dbt run

    - name: Test dbt models
      run: |
        dbt test
